title: Suite Pastiche
description: Melbourne's hi-fi dance party for the socially engaged and sonically curious
url: https://suitepastiche.com
baseurl: ""
lang: en
timezone: Australia/Melbourne

email: mailto:hello@suitepastiche.com

header_pages:
  - about.md
  - tickets.md
  - listen.md
  - gallery.md

social:
  instagram_username: suitepastiche
  mixcloud_username: suitepastiche

theme: minima
markdown: kramdown

exclude:
  - node_modules
  - vendor
  - .bundle
  - _site
  - .sass-cache
  - .jekyll-cache
  - .DS_Store
  - Thumbs.db
  - .env
  - .env.*